global using Catalog.API;
global using Catalog.API.Infrastructure;
global using Catalog.API.Infrastructure.EntityTypeConfigurations;
global using Catalog.API.Model;
global using ServiceDefaults;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Options;
global using Npgsql;